In [1]:
import pandas as pd
import seaborn as  sns
import matplotlib.pyplot as plt

In [72]:
# data_dons = pd.read_csv("https://storage.data.gov.my/healthcare/blood_donations.csv")
# data_dons.head()

In [73]:
# data_dons.rename({
#     "blood_type" : "groupe_sanguins",
#     "donations"  : "dons"
# },inplace= True , axis= 1)

# data_dons.head()

In [74]:
#data_dons.to_csv("data_dons.csv", index = False)

In [75]:
df = pd.read_csv("transfusion.csv", encoding="latin1")

# Option B : Windows-1252 (Standard sous Windows)
#df = pd.read_csv("transfusion.csv", encoding="cp1252")

In [76]:
data1 = pd.read_csv("Data_sheet_1.csv")
data1.head()

,date,collected_total,collected_A,collected_B,collected_O,collected_AB,team_total,Individual_donate,demand_total,demand_A,...,platelet_collection_tx_units,platelet_collection_A,platelet_collection_B,platelet_collection_O,platelet_collection_AB,platelet_supply,platelet_supply_A,platelet_supply_B,platelet_supply_O,platelet_supply_AB
0,3/19/2012,3896.0,1224.0,996,1389,287,1100,2796,4600,1400,...,419.0,120.0,93.0,165.0,41.0,416.0,139.0,100.0,145.0,32.0
1,3/26/2012,3058.0,965.0,749,1081,263,1115,1943,4300,1400,...,279.0,81.0,74.0,104.0,20.0,416.0,118.0,94.0,165.0,39.0
2,04/02/2012,3055.0,923.0,851,1007,274,399.5,2655.5,4600,1500,...,455.0,128.0,119.0,158.0,50.0,341.0,102.0,92.0,118.0,29.0
3,04/09/2012,2887.0,908.0,782,991,206,505,2382,4700,1500,...,398.0,141.0,95.0,139.0,23.0,405.0,120.0,111.0,143.0,31.0
4,4/16/2012,2915.0,800.0,819,1046,250,543.5,2371.5,4700,1500,...,350.0,91.0,100.0,129.0,30.0,374.0,121.0,82.0,138.0,33.0

In [77]:
data1.shape

(639, 29)

In [78]:
data1.columns

Index(['date', 'collected_total', 'collected_A', 'collected_B', 'collected_O',
       'collected_AB', 'team_total', 'Individual_donate', 'demand_total',
       'demand_A', 'demand_B', 'demand_O', 'demand_AB', 'supply_total',
       'supply_A', 'supply_B', 'supply_O', 'supply_AB', 'platelet_collection',
       'platelet_collection_tx_units', 'platelet_collection_A',
       'platelet_collection_B', 'platelet_collection_O',
       'platelet_collection_AB', 'platelet_supply', 'platelet_supply_A',
       'platelet_supply_B', 'platelet_supply_O', 'platelet_supply_AB'],
      dtype='str')

In [79]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 639 entries, 0 to 638
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          639 non-null    str
 1   collected_total               639 non-null    float64
 2   collected_A                   639 non-null    float64
 3   collected_B                   639 non-null    str
 4   collected_O                   639 non-null    str
 5   collected_AB                  639 non-null    str
 6   team_total                    615 non-null    str
 7   Individual_donate             639 non-null    str
 8   demand_total                  639 non-null    int64
 9   demand_A                      639 non-null    int64
 10  demand_B                      639 non-null    int64
 11  demand_O                      639 non-null    int64
 12  demand_AB                     639 non-null    int64
 13  supply_total                  639 non-null    float64
 14  supply_A                      639 non-null    str
 15  supply_B                      639 non-null    str
 16  supply_O                      639 non-null    str
 17  supply_AB                     639 non-null    str
 18  platelet_collection           639 non-null    float64
 19  platelet_collection_tx_units  639 non-null    float64
 20  platelet_collection_A         639 non-null    float64
 21  platelet_collection_B         639 non-null    float64
 22  platelet_collection_O         639 non-null    float64
 23  platelet_collection_AB        639 non-null    float64
 24  platelet_supply               639 non-null    float64
 25  platelet_supply_A             639 non-null    float64
 26  platelet_supply_B             639 non-null    float64
 27  platelet_supply_O             639 non-null    float64
 28  platelet_supply_AB            639 non-null    float64
dtypes: float64(14), int64(5), str(10)
memory usage: 179.7 KB

In [80]:
data1["date"] = pd.to_datetime(data1["date"])

In [81]:
data_ecart = data1['date'].sort_values().diff().value_counts()
data_ecart  #Ecart entre les differente jours de demandes

date
7 days     564
14 days     13
0 days      13
6 days      12
1 days      10
4 days       5
5 days       5
8 days       4
3 days       3
2 days       3
35 days      2
38 days      1
10 days      1
42 days      1
9 days       1
Name: count, dtype: int64

In [82]:
data1["date"].duplicated().sum() #Verification des doublons des dates

np.int64(13)

In [83]:
# Vérifier les lignes ayant des dates répétées
doublons = data1[data1['date'].duplicated(keep=False)].sort_values('date')

print(doublons[['date', 'demand_total', 'supply_total', 'collected_total']].to_string()) # Est que les donnes des dates du meme jours se ressmenbles entres eux ??

          date  demand_total  supply_total  collected_total
145 2015-01-05          3450        3445.5          2726.65
184 2015-01-05          2910        2842.5          2392.20
146 2015-01-12          3350        3548.5          3903.15
185 2015-01-12          3950        3843.5          3522.00
147 2015-01-19          3550        3698.0          3256.15
186 2015-01-19          4080        4033.5          5189.80
148 2015-01-26          3100        3163.5          2149.90
187 2015-01-26          3880        3726.5          2976.60
288 2017-01-02          2150        2157.5          2077.70
249 2017-01-02          3340        3292.5          2629.95
250 2017-01-09          3350        3282.5          3001.45
289 2017-01-09          3700        3614.5          3172.35
251 2017-01-16          3050        3006.0          2002.85
290 2017-01-16          4050        3940.0          4509.05
252 2017-01-23          2550        2493.0          2538.85
291 2017-01-23          4250        4221.0          4070.45
301 2018-01-01          2880        2846.0          2634.25
340 2018-01-01          3400        3413.5          3849.85
341 2018-01-08          3800        3805.5          3707.15
302 2018-01-08          3800        3755.0          3268.20
303 2018-01-15          3230        3180.5          2518.10
342 2018-01-15          4000        3952.5          3604.00
343 2018-01-22          4200        4157.5          4884.35
304 2018-01-22          3210        3180.5          2499.85
305 2018-01-29          3100        3131.0          3584.30
344 2018-01-29          4300        4272.0          3703.20

Apres analyse on remarques les donnees de demandes , de collectes ... du meme jours ne se ressembles pas

In [84]:
data1.columns

Index(['date', 'collected_total', 'collected_A', 'collected_B', 'collected_O',
       'collected_AB', 'team_total', 'Individual_donate', 'demand_total',
       'demand_A', 'demand_B', 'demand_O', 'demand_AB', 'supply_total',
       'supply_A', 'supply_B', 'supply_O', 'supply_AB', 'platelet_collection',
       'platelet_collection_tx_units', 'platelet_collection_A',
       'platelet_collection_B', 'platelet_collection_O',
       'platelet_collection_AB', 'platelet_supply', 'platelet_supply_A',
       'platelet_supply_B', 'platelet_supply_O', 'platelet_supply_AB'],
      dtype='str')

In [85]:
manque = data1.isnull().mean().sort_values(ascending=False)
manque = manque*100
manque.round(2)

team_total                      3.76
collected_total                 0.00
collected_A                     0.00
collected_B                     0.00
date                            0.00
collected_O                     0.00
collected_AB                    0.00
Individual_donate               0.00
demand_total                    0.00
demand_A                        0.00
demand_B                        0.00
demand_O                        0.00
demand_AB                       0.00
supply_total                    0.00
supply_A                        0.00
supply_B                        0.00
supply_O                        0.00
supply_AB                       0.00
platelet_collection             0.00
platelet_collection_tx_units    0.00
platelet_collection_A           0.00
platelet_collection_B           0.00
platelet_collection_O           0.00
platelet_collection_AB          0.00
platelet_supply                 0.00
platelet_supply_A               0.00
platelet_supply_B               0.00
platelet_supply_O               0.00
platelet_supply_AB              0.00
dtype: float64

In [86]:
data1.columns.tolist()

['date',
 'collected_total',
 'collected_A',
 'collected_B',
 'collected_O',
 'collected_AB',
 'team_total',
 'Individual_donate',
 'demand_total',
 'demand_A',
 'demand_B',
 'demand_O',
 'demand_AB',
 'supply_total',
 'supply_A',
 'supply_B',
 'supply_O',
 'supply_AB',
 'platelet_collection',
 'platelet_collection_tx_units',
 'platelet_collection_A',
 'platelet_collection_B',
 'platelet_collection_O',
 'platelet_collection_AB',
 'platelet_supply',
 'platelet_supply_A',
 'platelet_supply_B',
 'platelet_supply_O',
 'platelet_supply_AB']

In [87]:
tab = data1[["collected_A","collected_B", "collected_O", "collected_AB", "demand_A", "demand_B", "demand_AB", "demand_O"]]

In [88]:
tab

,collected_A,collected_B,collected_O,collected_AB,demand_A,demand_B,demand_AB,demand_O
0,1224.00,996,1389,287,1400,1400,400,1400
1,965.00,749,1081,263,1400,1300,300,1300
2,923.00,851,1007,274,1500,1500,400,1200
3,908.00,782,991,206,1500,1500,300,1400
4,800.00,819,1046,250,1500,1300,400,1500
...,...,...,...,...,...,...,...,...
634,1261.00,1265.25,1594.2,433.15,1200,1250,400,1450
635,1423.15,1289.3,1697.9,448.4,1500,1400,450,1700
636,1047.20,830.6,1154.75,275.5,1500,1300,400,1800
637,1621.35,1383.85,1704.6,448,1200,1400,300,1800
638,1756.95,1622.25,1957.65,502.95,1800,1500,500,2300

In [ ]:
nutri_data = pd.read_csv("malnutrition_data (1).csv")